### ISSUE TITLE
Migration files not created in migrations directory.

### ISSUE THREAD

**Issue by richarduren** [go-bun/bun-starter-kit#1]
The starter kit is great. Thanks for putting this together. 

One thing I've noticed, with the addition of the migration directory option in Bun, any migrations created in the starter-kit (create_sql & create_go) no longer create migrations in the migrations directory. They create them in the cmd/bun directory.

Setting the migrations directory in cmd/bun/migrations/main.go fixes the issue.

`
var Migrations = migrate.NewMigrations(migrate.WithMigrationsDirectory("migrations"))
`

**Comment by vmihailenco** [comment]
Thanks for the report. This should be fixed in v0.3.3 and bun-starter-kit master branch.
